language: android

android:
    components:
        - android-23
        - build-tools-23.0.1
        - platform-tools
        - extra-google-m2repository
        - extra-android-m2repository

 # ok no tests for now
 # - sys-img-x86-android-22

before_script:
    - GRADLE_OPTS="-Xms40m -Xmx3g -XX:MaxPermSize=3g"

script: "./gradlew clean build test -Dpre-dex=false"
